# Generated by Django 3.2.7 on 2021-09-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fecha_nacimiento',
        ),
    ]
