# Generated by Django 3.2.7 on 2021-09-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_remove_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_fin_contrato',
            field=models.DateField(null=True, verbose_name='Fecha Fin de Contrato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_inicio_contrato',
            field=models.DateField(null=True, verbose_name='Fecha Inicio de Contrato'),
        ),
    ]
