# Generated by Django 3.2.7 on 2021-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_alter_user_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_document', models.CharField(max_length=15, null=True, verbose_name='Número de Documento')),
            ],
        ),
    ]
